CREATE DATABASE QuanLy;
USE QuanLy;

-- Quản Lý Tài Khoản
CREATE TABLE TaiKhoan
(
    MaTK INT AUTO_INCREMENT PRIMARY KEY,
    UserName VARCHAR(100) NOT NULL,
    Pass VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Role ENUM('KhachHang', 'Admin') DEFAULT 'KhachHang',
    AccStatus TINYINT(1) DEFAULT 1,   -- Trạng thái tài khoản (1: kích hoạt, 0: vô hiệu hóa)
    AccCreDate DATETIME DEFAULT CURRENT_TIMESTAMP,
    AcUpdDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Quản Lý Khách Hàng
CREATE TABLE KhachHang 
(
    MaKH INT AUTO_INCREMENT PRIMARY KEY,
    TenKH VARCHAR(255) NULL,
    Email VARCHAR(255) NULL,
    DienThoai VARCHAR(15) NULL,
    DiaChi VARCHAR(255) NULL,
    MaTK INT,
    CONSTRAINT fk_khachhang_taikhoan FOREIGN KEY (MaTK) REFERENCES TaiKhoan(MaTK)
);

-- Quản Lý Rating, FeedBack
CREATE TABLE FeedBack 
(
    FeedBackID INT AUTO_INCREMENT PRIMARY KEY,
    MaKH INT NOT NULL,
    MaDH INT NOT NULL,
    MaRate VARCHAR(50) NULL,
    Rating INT NULL,
    Comment VARCHAR(255) NULL,
    CreDate DATETIME NULL,
    CreBy VARCHAR(50) NULL,
    CONSTRAINT fk_feedback_makh FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH),
    CONSTRAINT fk_feedback_madh FOREIGN KEY (MaDH) REFERENCES LichSuDatDon(MaDH)
);

-- Lịch Sử Đặt Đơn
CREATE TABLE LichSuDatDon
(
    MaDH INT AUTO_INCREMENT PRIMARY KEY,
    MaKH INT NOT NULL,
    OrderTime DATETIME NOT NULL,
    OrderStatus VARCHAR(50) NOT NULL,
    TotalPrice DECIMAL(10, 2) NOT NULL,
    PaymentMethod VARCHAR(50),
    DiaChi VARCHAR(255) NULL,
    LastUpdate TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT fk_order_makh FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH)
);
